application/content/routes.py
import redis
from flask import Blueprint, render_template, request, make_response, session, jsonify, redirect, url_for
from flask_login import login_required
from application.landing_page.forms import Quiz


content_bp = Blueprint('content_bp', __name__)
conn = redis.Redis('localhost', 6379, charset='utf-8', decode_responses=True)
leader_board = 'leaderboard'


@content_bp.route('/points', methods=['POST'])
@login_required
def points():
    """Adds one point to user's cumulative points and returns a JSON response indicating success or failure"""
    if request.method == 'POST':
        r = request.get_json()
        mission_number = r.get('mission')  # Mission which was completed
        if mission_number in session['missions']:  # If mission is valid
            if not session['missions'][mission_number]:  # If mission has not been completed before
                session['points'] = session.get('points') + 1
                session['missions'][mission_number] = True
                conn.zadd(leader_board, {session['username']: 1}, incr=True)  # updating our leaderboard with new points
                return make_response(jsonify({'message': 'points received and updated'}), 200)
            return make_response(jsonify({'message': 'mission done'}), 200)
        return make_response(jsonify({'message': 'invalid mission'}), 200)
    return make_response(jsonify({'error': 'invalid request'}), 400)


@content_bp.route('/leaderboard', methods=['GET'])
@login_required
def leaderboard():
    """Returns a sorted leaderboard in JSON format"""
    top_10 = conn.zrevrangebyscore(leader_board, 15, 1, start=0, num=10, withscores=True)
    return jsonify(top_10)


@content_bp.route('/story', methods=['GET'])
@login_required
def story():
    """The story and avatar"""
    return render_template('story.html', username=session['username'][:12], xp=session.get('points'),
                           done=session['missions'].values())


@content_bp.route('/about', methods=['GET'])
@login_required
def about():
    return render_template('about.html')


@content_bp.route("/profile", methods=['GET'])
@login_required
def profile():
    completed = session['missions'].values()
    if False in completed:
        return render_template('profile.html', username=session['username'][:12], xp=session.get('points'),
                               done=completed)
    return render_template('profile.html', username=session['username'][:12], xp=session.get('points'),
                           done=completed, badge=True)


# Missions aka Content #
@content_bp.route('/mission_1', methods=['GET', 'POST'])
@login_required
def mission_1():
    """Mission 1 and its contents"""
    return render_template('mission_1.html', username=session['username'][:12], xp=session.get('points'),
                           done=session['missions'].values())


@content_bp.route('/mission_2', methods=['GET', 'POST'])
@login_required
def mission_2():
    """Mission 2 and its contents"""
    return render_template('mission_2.html', username=session['username'][:12], xp=session.get('points'),
                           done=session['missions'].values())


@content_bp.route('/mission_3', methods=['GET', 'POST'])
@login_required
def mission_3():
    """Mission 3 and its contents"""
    return render_template('mission_3.html', username=session['username'][:12], xp=session.get('points'),
                           done=session['missions'].values())


@content_bp.route('/mission_4', methods=['GET', 'POST'])
@login_required
def mission_4():
    """Mission 4 and its contents"""
    return render_template('mission_4.html', username=session['username'][:12], xp=session.get('points'),
                           done=session['missions'].values())


@content_bp.route('/mission_5', methods=['GET', 'POST'])
@login_required
def mission_5():
    """Mission 5 and its contents"""
    return render_template('mission_5.html', username=session['username'][:12], xp=session.get('points'),
                           done=session['missions'].values())


@content_bp.route('/mission_6', methods=['GET', 'POST'])
@login_required
def mission_6():
    """Mission 6 and its contents"""
    return render_template('mission_6.html', username=session['username'][:12], xp=session.get('points'),
                           done=session['missions'].values())


@content_bp.route('/mission_7', methods=['GET', 'POST'])
@login_required
def mission_7():
    """Mission 7 and its contents"""
    return render_template('mission_7.html', username=session['username'][:12], xp=session.get('points'),
                           done=session['missions'].values())


@content_bp.route('/sidemission', methods=['GET', 'POST'])
@login_required
def quiz():
    """Quiz route aka side mission"""
    form = Quiz()
    if request.method == 'POST':
        if form.validate_on_submit():
            if not session['missions']['special']:  # If mission has not been completed before
                session['points'] = session.get('points') + 6
                session['missions']['special'] = True
                conn.zadd(leader_board, {session['username']: 6}, incr=True)
            if session['points'] >= 10:
                return render_template('success.html', username=session['username'], xp=session.get('points'))
            return redirect(url_for('content_bp.profile'))

    return render_template('quiz.html', form=form, username=session['username'][:12], xp=session.get('points'),
                           done=session['missions'].values())


@content_bp.route('/links', methods=['GET'])
@login_required
def links():
    """Just some extra links for additional reading"""
    return render_template('extra_read_allaboutit.html')

application/landing_page/routes.py
import redis
from flask import Blueprint, render_template, flash, url_for, redirect, request, session
from flask_login import login_required, current_user, logout_user, login_user
from application import login_manager
from .forms import LoginForm, SignupForm
from .models import db, User
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import escape


auth_bp = Blueprint('auth_bp', __name__)
conn = redis.Redis('localhost')
leader_board = 'leaderboard'


@auth_bp.route('/signup', methods=['GET', 'POST'])
def register():
    signup_form = SignupForm(request.form)
    if request.method == 'POST':
        if signup_form.validate():
            username = request.form.get('username')
            escaped_username = escape(username)
            if username != escaped_username:
                flash('Invalid characters detected')
                return redirect(url_for('auth_bp.register'))
            password = request.form.get('password')
            existing_user = User.query.filter_by(username=username).first()
            if existing_user is None:  # if no users are found, this is a new user
                user = User(username=username, password=generate_password_hash(password, method='sha256'), admin=False)
                db.session.add(user)
                db.session.commit()
                login_user(user)
                session['points'] = 0
                session['missions'] = {0: False, 1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False,
                                       'special': False}
                session['username'] = username
                return redirect(url_for('content_bp.story'))
            flash('Username taken')
            return redirect(url_for('auth_bp.register'))
    return render_template('signup.html', form=signup_form)


@auth_bp.route('/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('content_bp.story'))  # If user is logged in, send them to the story page
    login_form = LoginForm(request.form)
    if request.method == 'POST':
        if login_form.validate():
            username = request.form.get('username')
            password = request.form.get('password')
            user = User.query.filter_by(username=username).first()
            if user:
                if check_password_hash(user.password, password):
                    login_user(user)
                    session['points'] = 0
                    session['missions'] = {0: False, 1: False, 2: False, 3: False, 4: False, 5: False, 6: False,
                                           7: False, 'special': False}
                    session['username'] = username
                    next = request.args.get('next')
                    return redirect(next or url_for('content_bp.story'))
            flash('Invalid Username/Password combination')
            return redirect(url_for('auth_bp.login'))
    return render_template('login_new.html', form=login_form)


@auth_bp.route('/cookie-policy', methods=['GET'])
def cookie():
    return render_template('cookie_policy.html')


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    conn.zrem(leader_board, session['username'])  # remove username from leaderboard
    session.pop('username', None)
    return redirect(url_for('auth_bp.login'))


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))

application/templates/about.html
{%  extends "story.html" %}


    {% block title %}About{% endblock %}
    {% block head %}{% endblock %}
    {% block body %}
    {% block nav %} {{ super() }} {% endblock %}

    <div class="container">

        <h3>About:</h3>

        <p>
            This site was created by <em style="color:orange">Henri Nurmi, Nicolas Kyejo, and Petri Kölhi</em> as an innovation project for the course
            <em style="color:#3498DB">"Innovation Project XX00BH18-3282"</em> in Metropolia University of Applied Sciences during the autumn semester of 2019.
        </p>

        <p>
            The aim of the project was to create a web app to guide students during their orientation week at school. For further information or bug reports
            please email any of the authors above <em style="color:#3498DB">(firstname.lastname@metropolia.fi)</em>.
        </p>

    </div>

{% endblock %}

application/templates/mission_2.html
{%  extends "story.html" %}
{% block title %}Mission 2{% endblock %}
{% block head %}{{ super() }}{% endblock %}
{% block body %}

    {% block nav %} {{ super() }} {% endblock %}

    <div class="row">

    <div class="col-lg-auto">
            <div class="list-group">
{#                <a href="{{ url_for('content_bp.story') }}" class="list-group-item list-group-item-action">#}
{#                    Start#}
{#                </a>#}
{#                <a href="{{ url_for('content_bp.mission_1') }}" class="list-group-item list-group-item-action">#}
{#                    Mission 1#}
{#                </a>#}
{#                <a href="#" class="list-group-item list-group-item-action active">#}
{#                    Mission 2#}
{#                </a>#}
{#                <a href="{{ url_for('content_bp.mission_3') }}" class="list-group-item list-group-item-action disabled">#}
{#                    Mission 3#}
{#                </a>#}
{#                <a href="{{ url_for('content_bp.mission_4') }}" class="list-group-item list-group-item-action disabled">#}
{#                    Mission 4#}
{#                </a>#}
{#                <a href="{{ url_for('content_bp.mission_5') }}" class="list-group-item list-group-item-action disabled">#}
{#                    Mission 5#}
{#                </a>#}
{#                <a href="{{ url_for('content_bp.mission_6') }}" class="list-group-item list-group-item-action disabled">#}
{#                    Mission 6#}
{#                </a>#}
{#                <a href="{{ url_for('content_bp.mission_7') }}" class="list-group-item list-group-item-action disabled">#}
{#                    Mission 7#}
{#                </a>#}
        {% for mission in done %}
            {% if mission %}
                {% if loop.first %}
                    <a href="{{ url_for('content_bp.story') }}" class="list-group-item list-group-item-action active">
                    Start</a>
                {% elif loop.last %}
                    {# do nothing #}
                {% else %}
                <a href="{{ url_for('content_bp.mission_{0}'.format(loop.index - 1)) }}" class="list-group-item list-group-item-action active">
                    Mission {{ loop.index - 1 }}</a>
                {% endif %}

            {% else %}
                {% if loop.first %}
                    <a href="{{ url_for('content_bp.story') }}" class="list-group-item list-group-item-action disabled">
                    Start</a>
                {% elif loop.last %}
                    {# do nothing #}
                {% else %}
                <a href="{{ url_for('content_bp.mission_{0}'.format(loop.index - 1)) }}" class="list-group-item list-group-item-action disabled">
                    Mission {{ loop.index - 1 }}</a>
                {% endif %}
            {% endif %}
        {% endfor %}
            </div>
        </div>

    <div class="col-lg-6">

<h2>OMA workspaces</h2>
<p>On the top left of the homepage should be an <span style="color:orange">area dedicated to workspaces</span>.
    These are your courses that you have enrolled into, along with some useful groups e.g.
    OPO workspace that the OPOs use to communicate important information to you.
    You should be able to find the current course workspace that is starting this/next week. <span style="color:orange">Navigate into that</span>. </p>
<p>On the workspace frontpage you will find usually some information of the course along with a timeline.
    On the left you will find a navigation menu similar to the one displayed in the figure.</p>
<img src="{{ url_for('static', filename='img/workspace1.png') }}" ><br>
<p><span style="color:orange">Documents and assignments are the most useful of these</span>.
    Documents should have all the materials you need for the course, and assignments is where you return given assignments to.
    Familiarise yourself with these. </p>
<P>Next return to the OMA homepage and locate the OPO workspace.
    For your mission, you have to <span style="color:orange">locate in there your groups' course selection for the year along with the timeline</span>.
    Once complete, mark this mission as done. </P>

        <button type="button" class="btn btn-success" id="points_button">Bravo Mission Complete!</button><br>
    </div>
    <div class="col-sm-1">
        <h4 style="color:#F39C12">{{ username }}</h4>
        <img id="robohash" src="https://robohash.org/{{username}}.png" style="width:100px; height:100px; display:none;">
    </div>
    <div class="col-sm-1">
        <h4>XP <br></h4>
        <p id="points">{{ xp }}</p>
        Story progress
        <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 14.3%;" aria-valuenow="14.3" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>


    {% block leaderboard %} {{ super() }} {% endblock %}

    </div>

<script>
    $('#points_button').click(function () {

        $.ajax({
           data:JSON.stringify({points:1,mission:2}),
           url: "/points",
           type: "POST",
           contentType: "application/json",
           dataType: "json",
           processData: false,
           success:function(result) {
                console.log('POST success');
                console.log(result.message);
                setTimeout(function (){
                    window.location = '{{ url_for('content_bp.mission_3') }}'
                }, 400);
           },
           error: function (error) {
                console.log('POST fail')
           }
        })
    }

    );
</script>

{% endblock %}

application/templates/mission_3.html
{%  extends "story.html" %}
{% block title %}Mission 3{% endblock %}
{% block head %}{{ super() }}{% endblock %}
{% block body %}

    {% block nav %} {{ super() }} {% endblock %}

    <div class="row">

    <div class="col-lg-auto">
            <div class="list-group">
        {% for mission in done %}
            {% if mission %}
                {% if loop.first %}
                    <a href="{{ url_for('content_bp.story') }}" class="list-group-item list-group-item-action active">
                    Start</a>
                {% elif loop.last %}
                    {# do nothing #}
                {% else %}
                <a href="{{ url_for('content_bp.mission_{0}'.format(loop.index - 1)) }}" class="list-group-item list-group-item-action active">
                    Mission {{ loop.index - 1 }}</a>
                {% endif %}

            {% else %}
                {% if loop.first %}
                    <a href="{{ url_for('content_bp.story') }}" class="list-group-item list-group-item-action disabled">
                    Start</a>
                {% elif loop.last %}
                    {# do nothing #}
                {% else %}
                <a href="{{ url_for('content_bp.mission_{0}'.format(loop.index - 1)) }}" class="list-group-item list-group-item-action disabled">
                    Mission {{ loop.index - 1 }}</a>
                {% endif %}
            {% endif %}
        {% endfor %}
            </div>
        </div>

    <div class="col-lg-6">

<h2>Resources on OMA</h2>
        <img src="{{ url_for('static', filename='img/omafront1.png') }}" style="width: 99%;" ><br><br>
<p>There are <span style="color:orange">a lot of useful resources under OMA’s navigation bar</span>.
    Materials contain information about studies, student services, important dates and a lot more.
    Tools contain cloud services, MOT dictionaries, Turnitin and useful links, along with a list of other useful tools.</p>
<p>For your mission, <span style="color:orange">go through all the drop-down menus and find out the place where you can confirm your autumn/spring
    attendance</span>.
    Once done, mark yourself as complete.</p>

        <button type="button" class="btn btn-success" id="points_button">Charlie Mission Complete!</button><br>
    </div>
    <div class="col-sm-1">
        <h4 style="color:#F39C12">{{ username }}</h4>
        <img id="robohash" src="https://robohash.org/{{username}}.png" style="width:100px; height:100px; display:none;">
    </div>
    <div class="col-sm-1">
        <h4>XP <br></h4>
        <p id="points">{{ xp }}</p>
        Story progress
        <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 28.6%;" aria-valuenow="28.6" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>


    {% block leaderboard %} {{ super() }} {% endblock %}

    </div>

<script>
    $('#points_button').click(function () {

        $.ajax({
           data:JSON.stringify({points:1,mission:3}),
           url: "/points",
           type: "POST",
           contentType: "application/json",
           dataType: "json",
           processData: false,
           success:function(result) {
                console.log('POST success');
                console.log(result.message);
                setTimeout(function (){
                    window.location = '{{ url_for('content_bp.mission_4') }}'
                }, 400);
           },
           error: function (error) {
                console.log('POST fail')
           }
        })
    }

    );
</script>

{% endblock %}

application/templates/mission_4.html
{%  extends "story.html" %}
{% block title %}Mission 4{% endblock %}
{% block head %}{{ super() }}{% endblock %}
{% block body %}

    {% block nav %} {{ super() }} {% endblock %}

    <div class="row">

    <div class="col-lg-auto">
            <div class="list-group">
        {% for mission in done %}
            {% if mission %}
                {% if loop.first %}
                    <a href="{{ url_for('content_bp.story') }}" class="list-group-item list-group-item-action active">
                    Start</a>
                {% elif loop.last %}
                    {# do nothing #}
                {% else %}
                <a href="{{ url_for('content_bp.mission_{0}'.format(loop.index - 1)) }}" class="list-group-item list-group-item-action active">
                    Mission {{ loop.index - 1 }}</a>
                {% endif %}

            {% else %}
                {% if loop.first %}
                    <a href="{{ url_for('content_bp.story') }}" class="list-group-item list-group-item-action disabled">
                    Start</a>
                {% elif loop.last %}
                    {# do nothing #}
                {% else %}
                <a href="{{ url_for('content_bp.mission_{0}'.format(loop.index - 1)) }}" class="list-group-item list-group-item-action disabled">
                    Mission {{ loop.index - 1 }}</a>
                {% endif %}
            {% endif %}
        {% endfor %}
            </div>
        </div>

    <div class="col-lg-6">

<h2>Student desktop on OMA</h2>
<img src="{{ url_for('static', filename='img/student1.gif') }}" ><br><br>
<p>Here you can find your <span style="color:orange">student information</span> and on a quick glance check your student number or see how many credits you’ve accumulated.
    On top of that you can see a semester-based timeline of your credits.
    You can also give feedback for courses or pay your student union membership fee here.</p>
<img src="{{ url_for('static', filename='img/metka1.png') }}" ><br><br>

<h2>eHOPS or ePSP</h2>
<p>Access this from the navigation bar on the student desktop.
    eHOPS shows you your study path along with your grades.
    This will get filled up once you’ve chosen your major;
    It will also count your average grade.
    Furthermore, here is where you will do your course enrolments.
    </p><p>Your OPO (student advisor) will give you further instruction on those sometime in November or May.
    For your mission, <span style="color:orange">find the enrolment-page and search for a course that is available for enrolment</span>.
    <span style="color:red">Do not enroll!</span> But instead mark this part complete. </p>

        <button type="button" class="btn btn-success" id="points_button">Delta Mission Complete!</button><br>
    </div>
    <div class="col-sm-1">
        <h4 style="color:#F39C12">{{ username }}</h4>
        <img id="robohash" src="https://robohash.org/{{username}}.png" style="width:100px; height:100px; display:none;">
    </div>
    <div class="col-sm-1">
        <h4>XP <br></h4>
        <p id="points">{{ xp }}</p>
        Story progress
        <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 42.9%;" aria-valuenow="42.9" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>


    {% block leaderboard %} {{ super() }} {% endblock %}

    </div>

<script>
    $('#points_button').click(function () {

        $.ajax({
           data:JSON.stringify({points:1,mission:4}),
           url: "/points",
           type: "POST",
           contentType: "application/json",
           dataType: "json",
           processData: false,
           success:function(result) {
                console.log('POST success');
                console.log(result.message);
                setTimeout(function (){
                    window.location = '{{ url_for('content_bp.mission_5') }}'
                }, 400);
           },
           error: function (error) {
                console.log('POST fail')
           }
        })
    }

    );
</script>

{% endblock %}

application/templates/story.html
{% extends "base.html" %}
{% block title %}Story{% endblock %}
{% block head %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/story.js') }}"></script>
{% endblock %}

{% block body %}
    {% block nav %}

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
              <div class="navbar-collapse collapse" id="navbarColor02">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item">
                    <a class="nav-link" href={{ url_for('content_bp.story') }}>Story</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href={{ url_for('content_bp.profile') }}>Profile</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href={{ url_for('content_bp.about') }}>About</a>
                  </li>
                </ul>
                <form action="{{ url_for('auth_bp.logout') }}">
                  <button class="btn btn-danger disabled" id="logout" type="submit">Logout</button>
                </form>
              </div>
            </nav>


    {% endblock %}

    <div class="row">

        <div class="col-lg-auto">
            <div class="list-group">

        {% for mission in done %}
            {% if mission %}
                {% if loop.first %}
                    <a href="{{ url_for('content_bp.story') }}" class="list-group-item list-group-item-action active">
                    Start</a>
                {% elif loop.last %}
                    {# do nothing #}
                {% else %}
                <a href="{{ url_for('content_bp.mission_{0}'.format(loop.index - 1)) }}" class="list-group-item list-group-item-action active">
                    Mission {{ loop.index - 1 }}</a>
                {% endif %}

            {% else %}
                {% if loop.first %}
                    <a href="{{ url_for('content_bp.story') }}" class="list-group-item list-group-item-action disabled">
                    Start</a>
                {% elif loop.last %}
                    {# do nothing #}
                {% else %}
                <a href="{{ url_for('content_bp.mission_{0}'.format(loop.index - 1)) }}" class="list-group-item list-group-item-action disabled">
                    Mission {{ loop.index - 1 }}</a>
                {% endif %}
            {% endif %}
        {% endfor %}
            </div>
        </div>

        <div class="col-lg-6">


                <h4>That's you!</h4>
                <img id="robohash" src="https://robohash.org/{{username}}.png" style="display:none;"> <br>


                    <p>Welcome <span style="color:limegreen">Tursas</span>. Now that you have gotten your new identity as a student of information and communications technology, it is time to learn a few things.</p>
                    <p>We know that the first few days can be a bit overwhelming.
                        Never worry, things will get clearer with time.
                        For now, you are to set out on a set of missions to <span style="color:orange">get to know your way around the Metropolia platforms</span>.
                        We will keep score on how you’re getting along and you can compare yourself to your classmates on the leaderboard.</p>
                    <p>Make sure to complete each mission with some thought and feel free to revisit any of them later for a recap.
                        Once you are done, there is a side mission about your knowledge of Metropolia as a whole.
                        <span style="color:orange">Feel free to contact your tutors if you have any questions</span>! Once you are ready and briefed, get going! 👏👏👏 </p>
                <button type="button" class="btn btn-success" id="points_button">Briefing Complete</button><br>
        </div>
         <div class="col-sm-2">
             <h4 style="color:#F39C12">{{ username }}</h4>

             <h4>XP <br></h4>
             <p id="points">{{ xp }}</p>
         </div>
        {% block leaderboard %}
        <div class="col-lg-auto">

            <h2>Leaderboard</h2>


        <table class="table table-hover" id="leaderboard">
          <thead>
            <tr>
              <th scope="col">Rank</th>
              <th scope="col">Username</th>
              <th scope="col">XP</th>
            </tr>
          </thead>
          <tbody>

          </tbody>
        </table>
        </div>
        {% endblock %}

    </div>


<script>
    $('#points_button').click(function () {

        $.ajax({
           data:JSON.stringify({points:1,mission:0}),
           url: "/points",
           type: "POST",
           contentType: "application/json",
           dataType: "json",
           processData: false,
           success:function(result) {
                console.log('POST success');
                console.log(result.message);
                setTimeout(function (){
                    window.location = '{{ url_for('content_bp.mission_1') }}'
                }, 400);
           },
           error: function (error) {
                console.log('POST fail')
           }
        })
    }

    );
</script>
{% endblock %}

application/templates/success.html
{%  extends "story.html" %}
{% block title %}About{% endblock %}
{% block head %}<script>
  // https://developers.google.com/youtube/player_parameters
  // Load the IFrame Player API code asynchronously.
  var tag = document.createElement('script');
  tag.src = "http://www.youtube.com/player_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  // Replace the 'ytplayer' element with an <iframe> and
  // YouTube player after the API code downloads.
  var player;
  function onYouTubePlayerAPIReady() {
    player = new YT.Player('ytplayer', {
      height: '360',
      width: '640',
      videoId: 'VoAfb3f04mo',
      autoplay: '1'
    });

	const tileSize = 54;
	const numTiles = 24;
	const uiWidth = 4;

	x = y = 0;
	spritesheet = new Image();
	spritesheet.src = "{{ url_for('static', filename='img/metro.png') }}";

	document.querySelector("html").onkeypress = function(e){
		if (e.key === 'w') y--;
		if (e.key === 's') y++;
		if (e.key === 'a') x--;
		if (e.key === 'd') x++;
	};


	setInterval(draw, 15);
	setupCanvas();

  function setupCanvas() {
	canvas = document.querySelector('canvas');
	ctx = canvas.getContext('2d');

	canvas.width = tileSize * (numTiles + uiWidth);
	canvas.height = tileSize * numTiles;
	canvas.style.width = canvas.width + 'px';
	canvas.style.height = canvas.height + 'px';
	ctx.imageSmoothingEnabled = false;
}

function drawSprite(sprite, x, y) {
    ctx.drawImage(
        spritesheet,
        sprite*16,
        0,
        16,
        16,
        x*tileSize,
        y*tileSize,
        tileSize,
        tileSize
        );
}

function draw() {
	ctx.clearRect(0,0, canvas.width, canvas.height);
	drawSprite(0, x, y);
}
  }
</script>{% endblock %}
{% block body %}
{% block nav %} {{ super() }} {% endblock %}

    <div class="container">

        <h3>Congrats!</h3>
        <p>
            You did it! You were able to lead <span style="color:orange">{{ username }}</span> to the end!
            You finished with <span style="color:lightblue">{{ xp * 100 }}</span> experience points!
        </p>
        <p>
            Next week is when your studies start, keep your head up and remember to have fun! 😎&#9749;
        </p>
<div id="ytplayer"></div><br>
    <a href="{{ url_for('content_bp.links') }}">Extra stuff!</a><br>
    <a href="{{ url_for('content_bp.story') }}">Return to home page</a>
    </div>
    <canvas></canvas>

{% endblock %}